---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 7.12.0
  nodeSets:
  - name: master-nodes
    count: 2
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      cluster.routing.allocation.awareness.attributes: zone
      cluster.routing.allocation.awareness.force.zone.values: us-central1-a,us-central1-b,us-central1-c
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        - name: install-plugins
          command: ["sh", "-c", "bin/elasticsearch-plugin install --batch repository-gcs repository-s3"]
        nodeSelector:
          module: elastic-common
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: test
              topologyKey: kubernetes.io/hostname
        tolerations:
        - key: "module"
          operator: "Equal"
          value: "elastic"
          effect: "NoSchedule"

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard-rwo

  - name: coordinator
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        - name: install-plugins
          command: ["sh", "-c", "bin/elasticsearch-plugin install --batch repository-gcs repository-s3"]
        nodeSelector:
          module: elastic-common
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: test
              topologyKey: kubernetes.io/hostname
        tolerations:
        - key: "module"
          operator: "Equal"
          value: "elastic"
          effect: "NoSchedule"
        volumes:
        - name: elasticsearch-data
          emptyDir: {}

  - name: data-a
    count: 1
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      node.attr.zone: us-central1-a
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms7g -Xmx7g
          resources:
            requests:
              memory: 10Gi
              cpu: 1
            limits:
              memory: 14Gi
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        - name: install-plugins
          command: ["sh", "-c", "bin/elasticsearch-plugin install --batch repository-gcs repository-s3"]
        nodeSelector:
          module: elastic-data
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: test
              topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-central1-a
        tolerations:
        - key: "module"
          operator: "Equal"
          value: "elastic"
          effect: "NoSchedule"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard-rwo

  - name: data-b
    count: 1
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      node.attr.zone: us-central1-b
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms7g -Xmx7g
          resources:
            requests:
              memory: 10Gi
              cpu: 1
            limits:
              memory: 14Gi
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        - name: install-plugins
          command: ["sh", "-c", "bin/elasticsearch-plugin install --batch repository-gcs repository-s3"]
        nodeSelector:
          module: elastic-data
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: test
              topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-central1-b
        tolerations:
        - key: "module"
          operator: "Equal"
          value: "elastic"
          effect: "NoSchedule"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: es-test-coordinator-nodes
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: "test"
    elasticsearch.k8s.elastic.co/node-master: "false"
    elasticsearch.k8s.elastic.co/node-data: "false"
    elasticsearch.k8s.elastic.co/node-ingest: "false"
    elasticsearch.k8s.elastic.co/node-ml: "false"